### ISSUE TITLE
Not working on Buddypress Registration form

### ISSUE THREAD

**Issue by siparker** [Trumani/stop-spammers#155]
I have been having some issues on a client site where they are getting a lot of spammers registering using Hushmail.com email addresses.
I added the hushmail domain under Block Lists > Blocked TLD's and thought I was done, I can still see hushmail.com signups in the pending user's folder.
Is that normal behaviour for a blocked TLD? to add it to the pending folder?
I am unsure as this site specifically sends all new signups to pending so they can be managed individually. 
I need to find a way to essentially just block registrations for specific email address TLD's altogether which i thought SS might do.

Thanks

**Comment by bhadaway** [comment]
Hi siparker,

So what you're trying to block is actually the domain, that's what hushmail.com is.

The TLD (top-level domain) is only the .com part of it, so this won't be helpful to your goal and obviously you wouldn't want to block all of .com.

The plugin actually has a feature to block disposable email addresses like hushmail.com, but it needs to be updated. This option is set under:

_Stop Spammers > Protection Options > Deny Disposable Email Addresses_

Done! I've just added over 2,500 new disposable email domains (including hushmail) to the list. This will be in the next update (2020.4), which is coming soon.

Thanks

**Comment by siparker** [comment]
Hi,

I have already tried adding hushmail.com into the array for the disposable emails but the registrations still are not blocked.

They still appear in the pending folder.

Is this expected behaviour? potential spam signup goes to the pending folder?

**Comment by bhadaway** [comment]
You manually edited _chkdisp.php_?

Looks like it's not hushmail.**com**, but hushmail.**cf**.

By pending folder, you mean the Allow Requests list?

**Comment by siparker** [comment]
Yes i tried adding hushmail.com to that $disposables array in chkdisp

I want to block emails that end hushmail.com

the users with a hushmail.com email address are going into the pending folder of users. 

We have a plugin in place that means every user is manually approved. so everyone goes to pending

I was just checking if that would be what a user trying to use a disposable email would end up in also. or if the block is simply not working at all.

as it appears to not be working at all but im not sure how to get around that.

**Comment by bhadaway** [comment]
You're positive it's hushmail**.com**, and not hushmail**.cf**?

Also, what's the other plugin that you're using? It's difficult to say how well Stop Spammers plays with it. It's possible that that other plugin is circumventing Stop Spammers in some way or vice versa.

**Comment by siparker** [comment]
yes definately hushmail.com i want to block

https://i.imgur.com/vLc07ph.png

ill test turning that plugin off to see if it perhaps hooks in before the SS plugin does.

**Comment by siparker** [comment]
ok so i turned off the other plugin altogether and i can still get a registration through using hushmail.com

Not sure how to troubleshoot this any further as i believe this is now just vanilla buddypress registration with no other member plugins running...

**Comment by bhadaway** [comment]
Under:

_Stop Spammers > Protection Options > Only Use the Plugin for Standard WordPress Forms_

Is that box unchecked?
